version: '2'
services:
    tournamentcontrol-app:
        image: tournamentcontrol
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://tournamentcontrol-postgresql:5433/tournamentcontrol
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    tournamentcontrol-postgresql:
        extends:
            file: postgresql.yml
            service: tournamentcontrol-postgresql
